### ISSUE TITLE
GPTQModel support

### ISSUE THREAD

**Issue by Qubitium** [vkola-lab/PodGPT#1]
Please note GPTQModel will be soon merged into transformers/peft/optimum so the same auto-gptq training code will work but adapted using updated GPTQModel kernels and internal code. AutoGPTQ has various reasons, stopped development and GPTQModel is the likely replacement going forward. 

Tracking upstream merge here: https://github.com/ModelCloud/GPTQModel/issues/729

**Comment by SuperBruceJia** [comment]
> Please note GPTQModel will be soon merged into transformers/peft/optimum so the same auto-gptq training code will work but adapted using updated GPTQModel kernels and internal code. AutoGPTQ has various reasons, stopped development and GPTQModel is the likely replacement going forward.
> 
> Tracking upstream merge here: [ModelCloud/GPTQModel#729](https://github.com/ModelCloud/GPTQModel/issues/729)

Dear Qubitium and William (Qiwei), 

Well received with thanks! We will update our codebase with the development of the [GPTQModel](https://github.com/ModelCloud/GPTQModel).

Best regards,

Shuyue
Dec. 16th, 2024
